#BOARD=teensy:avr:teensy31:usb=disable,speed=96,opt=o1std,keys=en-us
#BOARD=teensy:avr:teensy31:usb=disable,speed=96,opt=o3purestd,keys=en-us
#BOARD=teensy:avr:teensy31:usb=disable,speed=96,opt=ogstd,keys=en-us
BOARD=teensy:avr:teensy36:usb=serial,speed=96,opt=o2std,keys=en-us
#-vid-pid=0X16C0_0X0483

PORT=/dev/ttyACM0
#PORT=/dev/ttyUSB0
MON_SPEED=115200
include ../Arduino_Make/_Makefile.master
